### ISSUE TITLE
How to Integrate rquery into my workflow?

### ISSUE THREAD

**Issue by harryprince** [WinVector/rquery#1]
I am a little bit curious about how to integrate rquery into my workflow.

I am using sparklyr and dplyr, some times sqldf daily.

sparklyr, dplyr ,sqldf looks integrate better than rquery.

**Comment by JohnMount** [comment]
rquery works well with sparklyr, the integration point is tables that have known names so rquery's DBI table source can model them.  

The purpose of rquery is to build very good SQL queries (safe and performant) on large tables including those that have a lot of columns (automatic query narrowing is one of rquery's advantages http://www.win-vector.com/blog/2017/12/how-to-greatly-speed-up-your-spark-queries/ ).  rquery is also excellent for saving and reasoning about query processing trees.

On the minus- rquery is still in early development.  Our group is working on it and working on the necessary documentation and training that will expose advantages to users.
