### ISSUE TITLE
Wonder if a disk.frame connector is possible? 

### ISSUE THREAD

**Issue by xiaodaigh** [WinVector/rquery#13]
Interesting in learning about the technical feasibility of connecting rquery to diskframe.com

**Comment by JohnMount** [comment]
I haven't researched it yet, but it should be feasible.  `rquery` is designed so that the connectors/adapters are supposed to be easy to build.  Do you have a preferred diskframe starting guide?

**Comment by xiaodaigh** [comment]
https://diskframe.com/articles/intro-disk-frame.html

If u have rquery for data.table then I think disk.frame should be possible. 

It's very dense and takes some time to understand. I think the read me can benefit from some dead simple examples. Like how does mutate and filter look like in rquery. Perhaps a side by side comparison in a table?

**Comment by JohnMount** [comment]
My group isn't looking to pursue adding a `disk.frame` adaptor at this time.

To anybody who wants to write such an adaptor: I would suggest looking into [`rqdatatable`](https://CRAN.R-project.org/package=rqdatatable).  `rqdatatable` is essentially just a list of the `rquery` verbs, each with a direct `data.table` realization (so the whole package is just a side by side comparison).  All one would have to do is not perform any of the `data.frame` to `data.table` casts or constructions (i.e. insist that all objects come to the methods as already `disk.frame` classes).

**Comment by JohnMount** [comment]
If you want to pursue an `rquery` `disk.frame` adapter: simpler `rquery` documentation is available [here](https://github.com/WinVector/rquery/blob/master/Examples/Introduction/rquery_Introduction.md), and `rqdatatable` (which the `rquery` `data.table` adapter) has been simplified in version `1.2.4`.
