### ISSUE TITLE
Spelling error.

### ISSUE THREAD

**Issue by prescient** [WinVector/rquery#16]
Super low priority error, but this error message appears to have a spelling mistake. I'm fairly sure duplicatge should be duplicate.

"Error in extend_impl(ndchain, parsedi, partitionby = partitionby, orderby = orderby,  : 
  rquery:::extend_impl **_duplicatge_** partitionby columns"

**Comment by JohnMount** [comment]
Sorry about that.  And thank you very much for taking the time to file an issue.  You are correct: that is a typo.   It is now fixed in the development version.
