### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by eribul** [WinVector/rquery#2]
I'm excited to try the package! Looks like really interesting work!!!

Found some dead links though on the  bottom of this page:
`https://winvector.github.io/rquery/`

* Join Controller
* Join Dependency Sorting
* Assignment Partitioner
* DifferentDBs

The same links are presented here (https://github.com/WinVector/rquery/).
Last ones refer to .md-files (works!), while the foirst goes to html (404 pages).

Thanks!

**Comment by JohnMount** [comment]
Thank you very much for filing the issue.

I've now run that down.  That is coming from a bug in pkgdown which translated working md-links from https://github.com/WinVector/rquery/blob/master/README.md to broken html-links in https://winvector.github.io/rquery/index.html .  

I have fixed the links one by hand and filed an [issue with pkgdown](https://github.com/r-lib/pkgdown/issues/763) (and [example](https://github.com/JohnMount/BrokenLinkExample/blob/master/README.md)).

I am looking for a work around idea on my end (perhaps run the links through an obscuring shortener so pkgdown can't see them as re-write opportunities).

**Comment by JohnMount** [comment]
I have a work around.

Relpace ".md" with "%2Emd" to hide the links from the processor.
