### ISSUE TITLE
Does rquery work with MonetDBLite?

### ISSUE THREAD

**Issue by waynelapierre** [WinVector/rquery#5]
I have been using dplyr with MonetDBLite for a while, and it literally solves all my problems in my work. I am curious about his rquery package. My first question is what difference does it make compared to the current tidyverse ecosystem? Second, does it work with MonetDBLite?

**Comment by JohnMount** [comment]
`rquery` generates more efficient queries, has semantics more consistent with Codd's relational algebra, and performs a lot more up-front checking.  Here are some [notes we have on `rquery`](http://www.win-vector.com/blog/tag/rquery/).  `rquery` hasn't been tested with`MonetDBLite`, so it probably would need to shaken down for that sort of application.  We are mostly targeting `Apache Spark` and `PostgreSQL` at the moment (plus in-memory with `rqdatatable`, where again it is often much faster than `dplyr`).

**Comment by JohnMount** [comment]
I checked.  `rquery` will need some translations define before it can work with `MonetDBLite`, so no it isn't ready for that database at this time.  It does have a translation layer- I just have not developed the `MonetDBLite` translations yet (likely maybe just uppercasing some common functions).  I'll add a note when I look into it. Thanks for your help.

**Comment by JohnMount** [comment]
Should not have closed this, sorry. I am not working on it right now, but do intend to get to this. Likely it is just changing case or synonyms for a few operators and `rquery` has a translation layer just for that.

**Comment by JohnMount** [comment]
The development version of `rquery` appears to work well with `MonetLiteDB`.  Some features are different (`MonetLiteDB` doesn't declare `sum()` as a window function), but I have a non-trivial working example [here](https://github.com/WinVector/rquery/blob/master/db_examples/MonetDBLite.md).
