### ISSUE TITLE
incomplete sentence in Readme

### ISSUE THREAD

**Issue by dpprdan** [WinVector/rquery#7]
In the [README.(R)md](https://github.com/WinVector/rquery/blob/master/README.md) the first sentence under the header "Discussion" reads:

> [`rquery`](https://github.com/WinVector/rquery) can be an excellent advanced `SQL` training tool (it shows how some very deep `SQL` by composing `rquery` operators).

I think the part in parenthesis is incomplete. 

One suggestion: Since the same text seems to be used in all Rmds in `db_examples` (I first saw it in [RPostgreSQL.md](https://github.com/WinVector/rquery/blob/master/db_examples/RPostgreSQL.md), via your [getting started blog post](http://www.win-vector.com/blog/2019/02/getting-started-with-rquery/)), using child documents as e.g. described in [this post](https://www.garrickadenbuie.com/blog/2018/03/05/dry-vignette-and-readme/) by @gadenbuie might be a good idea.

**Comment by JohnMount** [comment]
Thanks for the issue (and sorry about the typo).  I've made a quick fix. The child documents idea is interesting, I may play around with that.
